apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsq 
    role: service
  name: nsq 
spec:
  ports:
    - port: 4150
      name: tcp 
      targetPort: 4150
    - port: 4151
      name: http
      targetPort: 4151
  selector:
    nsq: "true"
