apiVersion: v1
kind: Pod
metadata:
  labels:
    name: nsq 
  name: nsq 
spec:
  containers:
    - name: nsq 
      image: nsqio/nsq 
      command: 
        - /nsqd
      ports:
        - containerPort: 4150
          name: tcp
          protocol: TCP
        - containerPort: 4150
          name: http
          protocol: TCP
      resources:
        limits:
          cpu: "0.1"
      volumeMounts:
        - mountPath: /data
          name: data
    - name: nsqlookup
      image: nsqio/nsq
      command:
        - /nsqlookupd
      ports:
        - containerPort: 4160
          name: tcp
          protocol: TCP
        - containerPort: 4160
          name: http
          protocol: TCP
  volumes:
    - name: data
      emptyDir: {}
