apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqlookup 
    role: service
  name: nsqlookup 
spec:
  ports:
    - port: 4160
      name: tcp 
      targetPort: 4160
    - port: 4161
      name: http
      targetPort: 4161
  selector:
    nsqlookup: "true"
